### DISCUSSION TITLE
Default Email Styles

### DISCUSSION THREAD

**Discussion by M-J-Robbins** [email-markup-consortium/email-markup-consortium#79] [General]
## Project title

Default Email Styles

## Project description

Based on [browserdefaultstyles.com](https://browserdefaultstyles.com/) this will show the default styles applied by email clients.  

For example on a `<td>` elements
**Yahoo webmail adds**
```css
.msg-body td {
    word-break: normal;
}
```
**Outlook webmail adds**
```css
._2Qk4AbDuWwkuLB005ds2jm td {
    white-space: normal!important;
}
```
**Gmail webmail adds**
```css
td{
    margin: 0;
    font-family: Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
    font-family: arial,sans-serif;
}
```

## Why is this needed

It will help highlight the differences in email client rendering.
It can help developers understand and fix unexpected rendering issues.
I can help understand what is needed for a CSS normalize.

## Scope

This will look at the styles added by the email clients, not at the styles added by the user agent as that is well covered by  [browserdefaultstyles.com](https://browserdefaultstyles.com/).

This will cover inline styles, embedded styles and linked styles as long as they affect the rendering of an email.

## Contributing members

@M-J-Robbins @rafaelfpviana

## Where will the project be worked on, and where will the finished project be hosted?

Built in a new github repo inside the EMC, starting by just collecting the data. This raw data can be useful on its own but then the next stage would be to create a user friendly view of this within the emailmarkup.org website.
